"""Plan / confirm REST endpoints (Task 4).

Two endpoints:

- ``POST /api/v1/plans`` — classify the user message and return a
  :class:`ResourcePlan` (no side effects, no job is created).
- ``POST /api/v1/plans/{plan_id}/confirm`` — start a job with the
  user-confirmed resource types.

The router is the orchestration boundary between the intent router
(deterministic, no LLM) and the :class:`JobRunner` (background
execution). It must NOT call any LLM itself.
"""

from __future__ import annotations

import uuid
from typing import Any

from fastapi import APIRouter, HTTPException

from tutor.services.intent.router import (
    VALID_CAPABILITIES,
    InvalidCapabilityError,
    classify,
)
from tutor.services.jobs import JobSubmit, get_job_runner
from tutor.services.resource_plan.schema import (
    ResourcePlan,
    ResourcePlanConfirmRequest,
    ResourcePlanRequest,
    SelectedResourceTypes,
)

router = APIRouter()

# Plan storage is intentionally in-memory: the plan is a transient
# handshake between the UI and the runner. If the user reloads the page
# the plan is gone, and they resubmit a fresh plan request. This is
# fine for the demo.
_PLANS: dict[str, dict[str, Any]] = {}


def _new_plan_id() -> str:
    return f"plan_{uuid.uuid4().hex[:12]}"


@router.post("/plans", response_model=ResourcePlan)
async def create_plan(req: ResourcePlanRequest) -> ResourcePlan:
    """Classify a user message and return a resource plan (no job yet)."""
    try:
        decision = classify(
            req.message,
            explicit_capability=req.explicit_capability,
        )
    except InvalidCapabilityError as exc:
        raise HTTPException(
            status_code=422,
            detail={
                "code": exc.code,
                "message": str(exc),
                "capability": exc.capability,
                "valid_capabilities": sorted(VALID_CAPABILITIES),
            },
        ) from exc
    if decision.capability != "resource_generation" or decision.resource_plan is None:
        raise HTTPException(
            status_code=422,
            detail=(
                f"intent is {decision.capability!r}, not resource_generation; "
                "no plan to confirm"
            ),
        )
    plan = decision.resource_plan
    # Persist the plan alongside the request metadata so /confirm can
    # look it up. plan_id was already generated by the router.
    _PLANS[plan.plan_id] = {
        "plan": plan,
        "request": req,
        "topic": decision.topic,
    }
    return plan


@router.post("/plans/{plan_id}/confirm")
async def confirm_plan(plan_id: str, req: ResourcePlanConfirmRequest) -> dict[str, Any]:
    """Confirm a plan and start a :class:`Job` with the selected types."""
    stored = _PLANS.get(plan_id)
    if stored is None:
        raise HTTPException(status_code=404, detail=f"plan not found: {plan_id}")
    plan: ResourcePlan = stored["plan"]
    original_req: ResourcePlanRequest = stored["request"]

    selected: SelectedResourceTypes = req.selected_types
    if not selected.types:
        raise HTTPException(status_code=422, detail="selected_types must be non-empty")

    # Merge: original request metadata + plan_id + selected types so the
    # resource_generation capability can pick them up.
    metadata = {
        **original_req.metadata,
        "plan_id": plan_id,
        "selected_resource_types": list(selected.types),
        "topic": plan.topic,
        "estimated_seconds": plan.estimated_seconds,
    }

    runner = get_job_runner()
    job = await runner.submit(
        JobSubmit(
            user_id=original_req.user_id,
            message=original_req.message,
            capability="resource_generation",
            language=original_req.language,
            metadata=metadata,
        )
    )
    # The plan is consumed; remove it from the in-memory store.
    _PLANS.pop(plan_id, None)
    return {
        "job_id": job.job_id,
        "plan_id": plan_id,
        "selected_types": list(selected.types),
        "topic": plan.topic,
        "estimated_seconds": plan.estimated_seconds,
        "status": job.status.value,
    }


__all__ = ["router"]
