"""Resource package service.

Models for the multi-modal learning resources generated by Tutor:

- :class:`Resource`       — a single resource (one of 7 types)
- :class:`ResourcePackage` — a bundle of resources for one topic + learner
- :class:`ResourceBuilder` — high-level helpers (assemble, validate, etc.)

Design follows idea.md closely. All Resource fields are JSON-serialisable so
the package can be persisted (Phase 5) and streamed to the frontend.
"""

from tutor.services.resource_package.schema import (
    CodeResource,
    DocumentResource,
    ExerciseOption,
    ExerciseQuestion,
    ExerciseResource,
    MindMapResource,
    PPTResource,
    ReadingResource,
    Resource,
    ResourcePackage,
    ResourceReview,
    ResourceType,
    ReviewVerdict,
    VideoResource,
    build_resource,
)

__all__ = [
    "CodeResource",
    "DocumentResource",
    "ExerciseOption",
    "ExerciseQuestion",
    "ExerciseResource",
    "MindMapResource",
    "PPTResource",
    "ReadingResource",
    "Resource",
    "ResourcePackage",
    "ResourceReview",
    "ResourceType",
    "ReviewVerdict",
    "VideoResource",
    "build_resource",
]
